### ISSUE TITLE
能否开放遮罩层颜色自定义

### ISSUE THREAD

**Issue by lucky1213** [GanZhiXiong/gzx_dropdown_menu#11]
能否开放遮罩层颜色自定义

**Comment by 1207915357** [comment]
赞同,希望大佬给个方法怎么自定义

**Comment by GanZhiXiong** [comment]
可以的，最近太忙了，都忘记fix bug了。
我会尽快抽时间解决fix bug和add new feature。
大家也可以PR！

**Comment by GanZhiXiong** [comment]
@luck
@1207915357 
这个问题已经解决，请用最新版本2.0.0！🤝
