### ISSUE TITLE
请假个问题 ,,主题颜色是白色 第一次点击下拉框颜色为白色字体颜色也是白色

### ISSUE THREAD

**Issue by luyi-word** [GanZhiXiong/gzx_dropdown_menu#13]
![微信图片_20191031180149](https://user-images.githubusercontent.com/54274687/67937579-ccf42100-fc08-11e9-99f5-028ab7c32873.jpg)

**Comment by GanZhiXiong** [comment]
<img width="803" alt="image" src="https://user-images.githubusercontent.com/27394631/81499984-c229ef80-9301-11ea-97b5-970e6d882a4f.png">
字体颜色是可以修改的，你看上图
