### ISSUE TITLE
急急急，如何在下拉弹窗下面添加确定和重置按钮，来选择筛选条件和重置

### ISSUE THREAD

**Issue by YinHAHA** [GanZhiXiong/gzx_dropdown_menu#15]
![image](https://user-images.githubusercontent.com/21334507/74604925-d218a580-50fd-11ea-8455-2317c08db973.png)

**Comment by GanZhiXiong** [comment]
@YinHAHA   你这个图片中不是已经实现了添加按钮吗？

**Comment by GanZhiXiong** [comment]
![image](https://user-images.githubusercontent.com/27394631/74649206-18333f00-51ba-11ea-9b03-328659f7b5b6.png)
你看readme或者example中的代码注释，我这个package的下拉区域你想显示什么完全由你自己决定

**Comment by GanZhiXiong** [comment]
@YinHAHA 
最新版本2.0.0+2发布了
你可以体验下最新版本，改动了不少。
下拉部分完全由使用者自己实现，我看你说的问题应该也不难，相信你已经解决了。
我要关闭这个Issue，如果还有其他问题请New issue。

**Comment by fanpengju** [comment]
使用中发现，下拉page 是 stuful，刚开始选择A，确定，然后在改选别的选项B之后，点击上边的tab的改变下标，然后再切换回来，选中了B， 而不是A

**Comment by GanZhiXiong** [comment]
@fanpengju  
没听太明白。
建议你贴下代码和截图。
如果这是一个新的issue，请添加一个新的issue。

**Comment by Lamda303** [comment]
@YinHAHA @GanZhiXiong 这样的页面，如果DropDowmWidget使用Column,Column里面是ListView(筛选项)+Container（确定和重置按钮），会由于显示或收起的动画过程中dropdownWidget的高度从0到最大变化，高度可能小于Container的widget而报错，这种情况怎么处理呢？
