### ISSUE TITLE
大佬，菜单头部，当激活A菜单时，直接激活B菜单，需要多点一下，能否优化下

### ISSUE THREAD

**Issue by lanxingye** [GanZhiXiong/gzx_dropdown_menu#16]
大佬，菜单头部，当激活A菜单时，直接激活B菜单，需要多点一下，能否调整为直接激活点击的那个逻辑。谢谢。

**Comment by lanxingye** [comment]
暴露下对应的设置方法，在GZXDropDownHeader中的onItemTap方法直接调，自己实现也可以

**Comment by lanxingye** [comment]
原来gzxDropdownMenuController.show(),可以直接实现。

**Comment by lanxingye** [comment]
但如果存在多个弹出菜单，会有问题

**Comment by GanZhiXiong** [comment]
@lanxingye 
这个问题已经解决，请用最新版本2.0.0！🤝
