### ISSUE TITLE
打算基于Provider去重构

### ISSUE THREAD

**Issue by 51bitquant** [GanZhiXiong/gzx_dropdown_menu#21]
你好，dropdownmenu一股浓浓的iOS味道，跟官方的代码差别很大，另外实际上代码的简洁性上可以优化下，可以基于Provider去做数据管理。这样会更好。

**Comment by GanZhiXiong** [comment]
这个package我这里是定义为轻量级，不会引入过多依赖，所以不打算引入Provider。

**Comment by GanZhiXiong** [comment]
后续会通过其他方式减少调用setstatue
