### ISSUE TITLE
header的宽度问题

### ISSUE THREAD

**Issue by zsfbest** [GanZhiXiong/gzx_dropdown_menu#23]
因为是用gridview的原因, 而宽高比的_menuCount又是从items的长度获取, item里面又是写死的类,希望改写下GZXDropDownHeader, itemcount由传入值或者可以传入childAspectRatio

**Comment by GanZhiXiong** [comment]
你说下你的需求吧？不太明白你要怎么控制header的宽度？

**Comment by CuoJue21** [comment]
> 你说下你的需求吧？不太明白你要怎么控制header的宽度？

请问 当header只有一个item的时候 希望是靠左显示 而不是居中显示应该如何设置

**Comment by zsfbest** [comment]
> > 你说下你的需求吧？不太明白你要怎么控制header的宽度？
> 
> 请问 当header只有一个item的时候 希望是靠左显示 而不是居中显示应该如何设置

我是重写了他的一个部件就可以了, dropdownheader

**Comment by zsfbest** [comment]
![image](https://user-images.githubusercontent.com/39234003/87373110-a2da6780-c5bb-11ea-8b9f-2f309a74530c.png)

**Comment by LiWangWu** [comment]
左边显示下拉菜单 右边显示搜索的控件 这样的场景使用不了?只会显示一小列
