### ISSUE TITLE
限制了父级必须是Stack

### ISSUE THREAD

**Issue by TinySungo** [GanZhiXiong/gzx_dropdown_menu#24]
在父级结构上，必须是Stack。
感觉使用Overlay实现更多通用，我在使用Overlay实现过程中，遇到了下拉动画如何实现的问题

**Comment by GanZhiXiong** [comment]
Overlay也是基于Stack。
我对Overlay不是很了解，你可以试试。
发现问题一起探讨！

**Comment by GanZhiXiong** [comment]
- 请问这个问题解决了吗？

由于长时间没有反馈，我将关闭这个Issue。若还有问题，请重新打开此Issue！
