### ISSUE TITLE
能否新增筛选常亮的选项

### ISSUE THREAD

**Issue by shetz163** [GanZhiXiong/gzx_dropdown_menu#27]
为了标识当前是筛选的状态 , 希望能在标签上增加常亮的选项 , 或者可以在GZXDropDownHeaderItem里增加TextStyle来控制每一个Item的文字未被激活时显示的样式

**Comment by GanZhiXiong** [comment]
![image](https://user-images.githubusercontent.com/27394631/83384910-cb970b00-a41a-11ea-9688-1ced4e0093e6.png)
dropDownStyle可以统一控制GZXDropDownHeaderItem激活时的样式。
要每个GZXDropDownHeaderItem都能控制样式的话，我后续会考虑添加这个功能

**Comment by GanZhiXiong** [comment]
![image](https://user-images.githubusercontent.com/27394631/83384910-cb970b00-a41a-11ea-9688-1ced4e0093e6.png)
dropDownStyle可以统一控制GZXDropDownHeaderItem激活时的样式。
要每个GZXDropDownHeaderItem都能控制样式的话，我后续会考虑添加这个功能

**Comment by shetz163** [comment]
可能是我表述的不太好，其实我想做到的是在没有激活dropdown的时候也能高亮显示的，所以我尝试着在GZXDropDownHeaderItem上加了style来控制这个样式，我可以发起一个pr来合并这段代码吗？

**Comment by GanZhiXiong** [comment]
可以的，欢迎贡献代码哈！👍

**Comment by GanZhiXiong** [comment]
最新版本V2.1.0刚刚发布，已添加此Feature。
**<u>[点我查看版本更新记录](https://pub.flutter-io.cn/packages/gzx_dropdown_menu#-changelog-tab-)</u>**

**Comment by shetz163** [comment]
第一次发起pr,还不是很会用这些功能.
