### ISSUE TITLE
clone下来显示Your app isn't using AndroidX.

### ISSUE THREAD

**Issue by liumingsongning** [GanZhiXiong/gzx_dropdown_menu#29]
> FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not resolve io.flutter:arm64_v8a_debug:1.0.0-9a28c3bcf40ce64fee61e807ee3e1395fd6bd954.
  Required by:
      project :app
   > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-9a28c3bcf40ce64fee61e807ee3e1395fd6bd954.
      > Could not get resource 'https://jcenter.bintray.com/io/flutter/arm64_v8a_debug/1.0.0-9a28c3bcf40ce64fee61e807ee3e1395fd6bd954/arm64_v8a_debug-1.0.0-9a28c3bcf40ce64fee61e807ee3e1395fd6bd954.pom'.
         > Could not HEAD 'https://jcenter.bintray.com/io/flutter/arm64_v8a_debug/1.0.0-9a28c3bcf40ce64fee61e807ee3e1395fd6bd954/arm64_v8a_debug-1.0.0-9a28c3bcf40ce64fee61e807ee3e1395fd6bd954.pom'.
            > Read timed out
> Could not resolve io.flutter:x86_64_debug:1.0.0-9a28c3bcf40ce64fee61e807ee3e1395fd6bd954.
  Required by:
      project :app
   > Could not resolve io.flutter:x86_64_debug:1.0.0-9a28c3bcf40ce64fee61e807ee3e1395fd6bd954.
      > Could not get resource 'https://jcenter.bintray.com/io/flutter/x86_64_debug/1.0.0-9a28c3bcf40ce64fee61e807ee3e1395fd6bd954/x86_64_debug-1.0.0-9a28c3bcf40ce64fee61e807ee3e1395fd6bd954.pom'.
         > Could not HEAD 'https://jcenter.bintray.com/io/flutter/x86_64_debug/1.0.0-9a28c3bcf40ce64fee61e807ee3e1395fd6bd954/x86_64_debug-1.0.0-9a28c3bcf40ce64fee61e807ee3e1395fd6bd954.pom'.
            > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 1s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by GanZhiXiong** [comment]
- 请问这个问题解决了吗？

由于长时间没有反馈，我将关闭这个Issue。若还有问题，请重新打开此Issue！
