### ISSUE TITLE
1.控件的header 无法完全填充，有一段，空白

### ISSUE THREAD

**Issue by zhengbiwenxs** [GanZhiXiong/gzx_dropdown_menu#34]
1.控件的header 无法完全填充，有一段，空白
2. 如何header 中items 只有一个值，只能显示在中间，去无法配置到靠左或者靠右显示

**Comment by 1227228155** [comment]
里面gridview的问题   自己重写  padding: EdgeInsets.all(0) 设置一下就行了

**Comment by GanZhiXiong** [comment]
- 请问这个问题解决了吗？
- 解决了说明下是gzx_dropdown_menu本身的问题，还是你的代码问题？

由于长时间没有反馈，我将关闭这个Issue。若还有问题，请重新打开此Issue！
