### ISSUE TITLE
没有appbar的情况下显示异常

### ISSUE THREAD

**Issue by MugWorld** [GanZhiXiong/gzx_dropdown_menu#35]
显示异常的情况是需要很高的高度才会显示gridview的内容

// var gridView = GridView.count(
    //   physics: NeverScrollableScrollPhysics(),
    //   crossAxisCount: _menuCount,
    //   childAspectRatio: (_screenWidth / _menuCount) / widget.height,
    //   children: widget.items.map<Widget>((item) {
    //     return _menu(item);
    //   }).toList(),
    // );
    var gridView = ListView(
      scrollDirection: Axis.horizontal,
      physics: NeverScrollableScrollPhysics(),
      children: widget.items.map<Widget>((item) {
        return _menu(item);
      }).toList(),
    );

然后改成这样才会显示正常

**Comment by MugWorld** [comment]
appBar: PreferredSize(
          child: AppBar(
            brightness: Brightness.dark,
            backgroundColor: Theme.of(context).primaryColor,
            elevation: 0,
          ),
          preferredSize: Size.fromHeight(-media.viewPadding.top)),好像可以通过这种处理

**Comment by sec7et** [comment]
> 显示异常的情况是需要很高的高度才会显示gridview的内容
> 
> // var gridView = GridView.count(
> // physics: NeverScrollableScrollPhysics(),
> // crossAxisCount: _menuCount,
> // childAspectRatio: (_screenWidth / _menuCount) / widget.height,
> // children: widget.items.map((item) {
> // return _menu(item);
> // }).toList(),
> // );
> var gridView = ListView(
> scrollDirection: Axis.horizontal,
> physics: NeverScrollableScrollPhysics(),
> children: widget.items.map((item) {
> return _menu(item);
> }).toList(),
> );
> 
> 然后改成这样才会显示正常

你好，我在一个不需要AppBar的页面上使用，用了你下面回复的方法设置了preferredSize，但是就会出现header点击不了的问题。这个情况你有碰到吗？

**Comment by sec7et** [comment]
0_0 好吧，似乎Scaffold并不是必须的，去掉就正常了。
