### ISSUE TITLE
如果第一个选项不需要下拉菜单，应该怎么实现？

### ISSUE THREAD

**Issue by jleisurely** [GanZhiXiong/gzx_dropdown_menu#37]
如果第一个选项不需要下拉菜单，应该怎么实现？

**Comment by Geek-James** [comment]
// 下拉菜单
          GZXDropDownMenu(
            // controller用于控制menu的显示或隐藏
            controller: _dropdownMenuController,
            // 下拉菜单显示或隐藏动画时长
            animationMilliseconds: 300,
            dropdownMenuChanging: (isShow, index) {
              if (index == 0) {
                // 第一个按钮不显示下拉框
                _dropdownMenuController.isShow = false;
              }
            },

**Comment by GanZhiXiong** [comment]
不建议在`dropdownMenuChanging`事件中控制是否需要下拉菜单。

正确的做法是在Header的`onItemTap`事件中控制：
``` dart
GZXDropDownHeader(
  // 当点击头部项的事件，在这里可以进行页面跳转或openEndDrawer
  onItemTap: (index) {
    if (index == 0) {
      _dropdownMenuController.hide();
      print('index == 0 hide');
    } else if (index == 3) {
      _dropdownMenuController.hide();
      _scaffoldKey.currentState!.openEndDrawer();
    }
  },
  ...
)  
```
