### ISSUE TITLE
大佬，flutter2发布了，快来写兼容版本

### ISSUE THREAD

**Issue by ashuicoder** [GanZhiXiong/gzx_dropdown_menu#40]
大佬，flutter2发布了，快来写兼容版本

**Comment by SilentSword2020** [comment]
可以支持flutter 2.0的空安全不？

**Comment by GanZhiXiong** [comment]
可以，这周发布兼容flutter2.0的版本。
最近实在太忙了，不然我还会发布更多实用的组件。

**Comment by hu70258tao** [comment]
@GanZhiXiong 七天前说这周,七天后我特地来催更.

**Comment by GanZhiXiong** [comment]
😂，感谢关注，工作实在有点忙，给忘记了。

**今晚上12点之前一定更新**

**Comment by ashuicoder** [comment]
> 😂，感谢关注，工作实在有点忙，给忘记了。
> 
> **今晚上12点之前一定更新**

大佬，还有6.5小时

**Comment by GanZhiXiong** [comment]
最近没时间关注flutter 2.0，所以我也不太清楚升级到Flutter2.0会对本package造成什么影响？

我更新了到了Flutter stable最新版本`2.0.3`
``` js
$ flutter --version
Flutter 2.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d7946a68d (2 weeks ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2
```

**运行没有任何问题啊
请提供错误信息！
Thanks！**

**Comment by GanZhiXiong** [comment]
抱歉，估计今晚等不到你们的回复了！
我先睡😪了！

**明天收到你们的回复我立马解决！**

**Comment by moxiaov587** [comment]
flutter 2.0的插件最好适配一下null safe，你可以先看看dart 2.12版本关于null safe的支持，使用官方的迁移工具迁移可以试试`dart migrate`命令

**Comment by GanZhiXiong** [comment]
@moxiaov587 
Thanks!
我试试！

**Comment by GanZhiXiong** [comment]
已经Migrate to null safety.
![image](https://user-images.githubusercontent.com/27394631/113415729-691fea00-93f2-11eb-803c-cfef0fe27e7f.png)

请使用最新版本`3.0.0`
如`gzx_dropdown_menu: ^3.0.0`

或者你也可以通过以下方式，将所有依赖包升级至支持空安全的最新版本。
### 1. 检查所有依赖的迁移状态（可跳过这步，直接使用第2步）
通过以下命令检查依赖包的迁移状态：
``` dart
dart pub outdated --mode=null-safety
```
![image](https://user-images.githubusercontent.com/27394631/113417036-29a6cd00-93f5-11eb-85a5-46b14913fbb6.png)
- Resolvable 列为已迁移至空安全的版本
- 打勾的版本号表示该版本号已支持空安全

### 2. 依赖升级至支持空安全的最新版本
运行以下命令将依赖升级至支持空安全的最新版本：
```dart
flutter pub upgrade --null-safety
```
注意： 该命令会更改您的 pubspec.yaml 文件。
![image](https://user-images.githubusercontent.com/27394631/113418032-40e6ba00-93f7-11eb-8ba1-7794ac1a5d0c.png)
