### ISSUE TITLE
下拉菜单头部上下可以滑动

### ISSUE THREAD

**Issue by shaonianahua** [GanZhiXiong/gzx_dropdown_menu#8]
![test](https://user-images.githubusercontent.com/40251305/63253097-c7db3300-c2a3-11e9-8648-80a65eea8aa1.PNG)
头部的地区 级别 类型那里 可以上下滑动 文字会随着手势上下滑动变化 这个可以解决吗

**Comment by shaonianahua** [comment]
下面的菜单开启和隐藏时都有这种情况

**Comment by GanZhiXiong** [comment]
最好录制个视频给我看看，没明白你的意思

**Comment by shaonianahua** [comment]
[demo.zip](https://github.com/GanZhiXiong/gzx_dropdown_menu/files/3515064/demo.zip)
发不了mp4 打成zip的包了

**Comment by GanZhiXiong** [comment]
这个问题，可以解决，我会抽时间解决。

解决后我会发布一个版本，到时候你使用我最新发布的版本就可以了

**Comment by shaonianahua** [comment]
好的 感谢

**Comment by xiongwenzhi** [comment]
可以滑动的问题 改好了吗？

**Comment by GanZhiXiong** [comment]
这周搞定吧，最近实在是比较忙

**Comment by xiongwenzhi** [comment]
好的，感谢

**Comment by fangshengfy** [comment]
可以自己修改GZXDropDownHeader.dart 中的
  var gridView = GridView.count(
      crossAxisCount: _menuCount,
      childAspectRatio: (_screenWidth / _menuCount) / widget.height,
      children: widget.items.map<Widget>((item) {
        return _menu(item);
      }).toList(),
    );
改为
  var gridView = GridView.count(
      physics: NeverScrollableScrollPhysics(),
    //加一句
      crossAxisCount: _menuCount,
      childAspectRatio: (_screenWidth / _menuCount) / widget.height,
      children: widget.items.map<Widget>((item) {
        return _menu(item);
      }).toList(),
    );

**Comment by ebwood** [comment]
> 可以自己修改GZXDropDownHeader.dart 中的
> var gridView = GridView.count(
> crossAxisCount: _menuCount,
> childAspectRatio: (_screenWidth / _menuCount) / widget.height,
> children: widget.items.map((item) {
> return _menu(item);
> }).toList(),
> );
> 改为
> var gridView = GridView.count(
> physics: NeverScrollableScrollPhysics(),
> //加一句
> crossAxisCount: _menuCount,
> childAspectRatio: (_screenWidth / _menuCount) / widget.height,
> children: widget.items.map((item) {
> return _menu(item);
> }).toList(),
> );

应该使用ClampingScrollPhysics才有效。不过作者好像都不更新了，我试试提个PR吧。

**Comment by GanZhiXiong** [comment]
@FakenMaster   
👍👍，欢迎贡献代码！提PR吧，我现在正在merge，merge完后我会发布一个新版本到pub

**Comment by ebwood** [comment]
> @FakenMaster
> 👍👍，欢迎贡献代码！提PR吧，我现在正在merge，merge完后我会发布一个新版本到pub

这个库还是很实用的。有一个问题就是没有保持滑动距离，这有点不太友好。

**Comment by GanZhiXiong** [comment]
@FakenMaster 
没有保持滑动距离指的是什么啊？

**Comment by ebwood** [comment]
@GanZhiXiong 
![test](https://user-images.githubusercontent.com/60820399/81472163-b6b6c580-9228-11ea-9a91-692831ab90bc.gif)
第一列的滚动距离不见了。

**Comment by GanZhiXiong** [comment]
> @GanZhiXiong
> 第一列的滚动距离不见了。

@FakenMaster 
目前还不考虑添加这个功能，dropdown menu部分尽量由使用者自己去实现

**Comment by GanZhiXiong** [comment]
@shaonianahua  @xiongwenzhi
这个问题已经解决，请用最新版本2.0.0！🤝
