### ISSUE TITLE
头部按钮多次点击后下面显示异常，如图

### ISSUE THREAD

**Issue by danayes** [GanZhiXiong/gzx_dropdown_menu#9]
![Screenshot_1566549055的副本](https://user-images.githubusercontent.com/5181038/63578618-755f8680-c5c3-11e9-8f30-c1cc4806443d.png)

**Comment by GanZhiXiong** [comment]
感谢你的反馈。这个周末我会抽时间解决！

**Comment by HyggeBo7** [comment]
> 感谢你的反馈。这个周末我会抽时间解决！

这个问题有没有解决呀？

**Comment by Jinxishihenian** [comment]
你可以试着用下这个组件 flutter_dropdown_menu 也是蛮不错的
![深度截图_选择区域_20191030184158](https://user-images.githubusercontent.com/44466363/67851241-fe0b1d80-fb44-11e9-8506-4ae623fec65e.png)

**Comment by Jinxishihenian** [comment]
1

**Comment by 284658474** [comment]
同样出现多次点击头部tab出现问题

**Comment by GanZhiXiong** [comment]
这个问题已经解决，请用最新版本2.0.0！🤝

**Comment by GanZhiXiong** [comment]
就等了哈，之前实在是太忙了，没有空维护！

**Comment by Jinxishihenian** [comment]
没关系的,我有需求需要用到类似的组件(顶部筛选),所以就去github看了一下.最后我使用了dropdown_menu.这个插件.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"干志雄"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月10日(星期天) 晚上6:34
收件人:&nbsp;"GanZhiXiong/gzx_dropdown_menu"<gzx_dropdown_menu@noreply.github.com&gt;;
抄送:&nbsp;"528890686"<528890686@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [GanZhiXiong/gzx_dropdown_menu] 头部按钮多次点击后下面显示异常，如图 (#9)





 
就等了哈，之前实在是太忙了，没有空维护！

**Comment by GanZhiXiong** [comment]
@Jinxishihenian 
好的，你也可以体验下最新版，最新版本做了很多改进。
dropdown_menu似乎已经很久没有更新了。
gzx_dropdown_menu我会持续保持更新。
